[SPRINT-1] INC-1-3
sreway/yametrics pull request #1
Opened 2022-05-29 13:34 UTC by sreway

2022-05-30 19:09 UTC, Perederey requested changes
В целом очень хорошо,
надо только переделать критическую штуку с рефлексией - ее будет тяжело дальше поддерживать, она плохо читается и замедляет работу 

Второе (но это мы поправим в течении следующих инкрементах) - работа с пакетом context и waitGroup

2022-05-30 19:09 UTC, Perederey commented on cmd/agent/main.go
> +)
круто было бы это дело в конфиг передать, например сделтаь струткуру и по-умолчанию ее заполнить значениями.

По поводу serverContentType не уверен, мне кажется хендлеры могут возвращать различные content/type json, plain, файлы и так далее

2022-05-30 19:09 UTC, Perederey commented on internal/agent/agent.go
> +func NewAgentConfig(poolInterval, reportInterval time.Duration, serverAddr string,
вижу, что у тебя хороший код, давай немного усложим для тебя задачу. Но это опционально:

Попробуй сделать так, что Agent и Server могут запускаться со значениями по-умолчанию, но ты можешь их переопределить с помощью функций `Options`.

https://www.sohamkamani.com/golang/options-pattern/ - вот тут подробнее о паттерне

2022-05-30 19:09 UTC, Perederey commented on internal/agent/agent.go
> +	wg         *sync.WaitGroup
а зачем тебе waitGroup в структуре?

2022-05-30 19:09 UTC, Perederey commented on internal/agent/agent.go
> +	ctx        context.Context
контекст тоже лучше передавать в функции, а не в структуре.
Контекст и его например отмена важны именно в функциях, а не в структурах. Поэтому его и передают первым аргументом в функции.

2022-05-30 19:09 UTC, Perederey commented on internal/agent/agent.go
> +	stopFunc   context.CancelFunc
тоже не нужно, 
если хочешь возьми 1:1 разберем с тобой context и почему функцию stop так не передают

2022-05-30 19:09 UTC, Perederey commented on internal/agent/agent.go
> +	defer a.wg.Done()
не совсем понятен вот этот финт. А зачем он тебе тут?

2022-05-30 19:09 UTC, Perederey commented on internal/agent/agent.go
> +				exitChan <- 0
обычно все вызовы передают через запятую, зачем обрабатывать все сигналы прям отдельно?

2022-05-30 19:09 UTC, Perederey commented on internal/agent/agent.go
> +	a.wg.Wait()
хм, забавно ты реализовал, но мне кажется это немного избыточно, я так понял, ты реализуешь что-то типа gracefull shutdown?

2022-05-30 19:09 UTC, Perederey commented on internal/agent/agent.go
> +	ctx, cancel := context.WithCancel(context.Background())
вот это тут лишние, писал выше про context, а waitGroup можно конечно попробовать использовать, как ты их хочешь - но мне кажется избыточно.

2022-05-30 19:09 UTC, Perederey commented on internal/agent/agent.go
> +		err = response.Body.Close()
лучше закрывать через defer, а так получается ты еще не успел считать и уже закрыл body

2022-05-30 19:09 UTC, Perederey commented on internal/agent/agent_test.go
> +
есть встроенный httptest.Server и httptest.Recorder в качестве writer, который поможет избежать вот таких избыточных конструкций.

2022-05-30 19:09 UTC, Perederey commented on internal/agent/agent_test.go
> +	statusCode int
еще бы body было классно добавить

2022-05-30 19:09 UTC, Perederey commented on internal/agent/collector.go
> +	Value interface{}
interface{} лучше бы не использовать.
Подумай, а как можно решить задачу без использования интерфейсов?

2022-05-30 19:09 UTC, Perederey commented on internal/agent/collector.go
> +	defer c.mu.Unlock()
👍

2022-05-30 19:09 UTC, Perederey commented on internal/agent/collector.go
> +	}
reflect в runtime использовать не стоит, он очень сильно замедляет приложение, да и читать такой код очень сложно (а значит и поддержитвать)

```
Clear is better than clever.
Reflection is never clear.
```

2022-05-30 19:09 UTC, Perederey commented on internal/metrics/metrics.go
> +	}
тоже самое, писал выше о рефлексии

2022-05-30 19:09 UTC, Perederey commented on internal/server/handlers.go
> +</html>`
кстати, можешь еще использовать с go1.16 embed и не хранить прямо в код html, он будет подругжен при компиляции. Это позволит поддерживать и редактировать html более просто.

2022-05-30 19:09 UTC, Perederey commented on internal/server/handlers.go
> +	}
тут не совсем так, у нас есть специальные методы «распаковки» ошибок, но пока ок. В уроке про ошибке исправим ;)

2022-05-30 19:09 UTC, Perederey commented on internal/server/handlers_test.go
> +	req, err := http.NewRequest(method, url, nil)
можно использовать httptest, а не http

2022-05-30 19:09 UTC, Perederey commented on internal/server/handlers_test.go
> +				t.Fatal(err)
`require.NoError()`

2022-05-30 19:09 UTC, Perederey commented on internal/server/server.go
> +	wg         *sync.WaitGroup
вот про это уже писал

2022-05-30 19:22 UTC, Perederey commented on internal/metrics/metrics.go
> +
тут, другого способа нет, так как мы смотрим runtime, по-другому никак.

2022-05-30 19:56 UTC, sreway commented on internal/agent/agent.go
> +func NewAgentConfig(poolInterval, reportInterval time.Duration, serverAddr string,
Ок на конфигами поработаю

2022-05-30 19:57 UTC, sreway commented on internal/agent/agent.go
> +	wg         *sync.WaitGroup
Мне показалась это не плохой идеей =) Ок поправлю

2022-05-30 19:57 UTC, sreway commented on internal/agent/agent.go
> +	ctx        context.Context
Ок так же поправлю

2022-05-30 19:58 UTC, sreway commented on internal/agent/agent.go
> +	stopFunc   context.CancelFunc
Ок спасибо, код только поправлю

2022-05-31 21:58 UTC, sreway commented on internal/server/handlers_test.go
> +				t.Fatal(err)
fixed

2022-05-31 21:59 UTC, sreway commented on internal/server/handlers_test.go
> +	req, err := http.NewRequest(method, url, nil)
fixed

2022-05-31 21:59 UTC, sreway commented on internal/server/handlers.go
> +	}
fixed

2022-05-31 21:59 UTC, sreway commented on internal/server/handlers.go
> +</html>`
fixed

2022-05-31 21:59 UTC, sreway commented on internal/agent/agent.go
> +	stopFunc   context.CancelFunc
fixed

2022-05-31 21:59 UTC, sreway commented on internal/agent/agent.go
> +	ctx        context.Context
fixed

2022-05-31 21:59 UTC, sreway commented on internal/agent/agent.go
> +	wg         *sync.WaitGroup
fixed

2022-05-31 21:59 UTC, sreway commented on internal/agent/agent.go
> +func NewAgentConfig(poolInterval, reportInterval time.Duration, serverAddr string,
Добавил

2022-06-02 07:14 UTC, Perederey approved these changes
отлично ;)

2022-06-02 08:22 UTC, merged