[SPRINT-2] INC-4-8
sreway/yametrics pull request #2
Opened 2022-06-20 22:25 UTC by sreway

2022-06-21 16:52 UTC, Perederey approved these changes
В целом хорошо! 
Добавил комменатрии, из важного:
1) надо упрощать код, разносить все на слоит - тогда код будет проще читать и поддерживать
2) обрати внимание на трудоемкие операции, которые можно вынести из цилка: из критичного - открытие файла при каждой записи в файл - лучше один раз открыть и закрыть файл, лишь когда закончишь работать с ним.

2022-06-21 16:52 UTC, Perederey commented on cmd/agent/main.go
> +func init() {
Лучше не объявлять флаги в `init()` - это первое, что загружается в пакете. И могут возникнуть проблемы, когда будешь добавлять код позже. Лучше сделать парсинг флагов в `main()`

2022-06-21 16:52 UTC, Perederey commented on internal/agent/agent.go
> +		endpoint := fmt.Sprintf("http://%s/%s", a.Config.ServerAddress, updateURI)
я думаю эти две задачи не нужно делать в цикле, они вообще могут быть частью agent, и когда будешь делать request, то просто передавать a.UpdateEndpoint, например

2022-06-21 16:52 UTC, Perederey commented on internal/agent/agent.go
> +		endpoint := fmt.Sprintf("http://%s/%s", a.Config.ServerAddress, updateURI)
А так получается, что на каждую итерацию метрики ты выделяешь память. Там конечно компилятор справится с таким и по-факту он загонит все это в констаты сам, но опять же зачем этот избыточный код в цикле

2022-06-21 16:52 UTC, Perederey commented on internal/server/handlers.go
> +	decoder.DisallowUnknownFields()
я был осторожен с такой штукой, обычно она нужна только для публичного api, но в целом прикольно, что использовал такую штуку.

2022-06-21 16:52 UTC, Perederey commented on internal/server/handlers.go
> +	w.Header().Set("content-type", "application/json")
Лучше использовать всегда Content-Type заголовки некоторых серверов и клиентов могут быть придирчивыми и важно соблюдать правильный формат. https://developer.mozilla.org/ru/docs/Web/HTTP/Headers/Content-Type

2022-06-21 16:52 UTC, Perederey commented on internal/server/handlers.go
> +	}
тут прям сложных кусочек кода, подумай как можно упросить этот код, убрать вложенности с ошибками, разные switch? 
Возможно выделить отдельные сущности для ошибок, отдельные для метрик?

2022-06-21 16:52 UTC, Perederey commented on internal/server/server.go
> +		}
а зачем тебе прям разные сигналы? Почему просто не получать один и просто выводить ошибку? Или закрывать процесс? Необходима ли такая сложность?

2022-06-21 16:52 UTC, Perederey commented on internal/server/server.go
> +	wg.Wait()
а может тебе waitGroup тут не нужен и просто ожидать exitChan?

2022-06-21 16:52 UTC, Perederey commented on internal/server/storage.go
> +	StorageMetrics map[string]map[string]interface{}
как-то я писал про interface{} в метрики. Лучше создать или использовать структуру, interface{} слишком общее название, там может быть массив, переменная, указатель, map[string]intreface тоже - вообщем проблем больше, чем пользы. Их используют конечно, но часто в функциях, а не способ возврата.
Я бы лучше заменил бы

2022-06-21 16:52 UTC, Perederey commented on internal/server/storage.go
> +	StorageMetrics map[string]map[string]interface{}
избыточная крейзи map какая-то получилась, подумаю как можно упросить хранение в памяти?

2022-06-21 16:52 UTC, Perederey commented on internal/server/storage.go
> +	fileObj, err := os.OpenFile(filePath, flag, 0644)
каждый раз открывать файл при каждой транзакции - рано или поздно произойдет ошибка, надо это дело поправить. 
Открытие в одном месте (при создании storage), закрытие при завершение программы, записись в моменте, но я бы тоже бы с ней был аккуратен.

2022-06-21 16:53 UTC, Perederey requested changes
И из главного и основного надо убрать interface{} из функции, и заменить их на структуру ;)

2022-06-24 14:02 UTC, sreway commented on internal/server/handlers.go
> +	}
fixed [change storage format](https://github.com/sreway/yametrics/pull/2/commits/bcc518d1be8d949e2baef6b8da0a23b8728e5c06)

2022-06-24 14:02 UTC, sreway commented on internal/server/storage.go
> +	StorageMetrics map[string]map[string]interface{}
fixed [change storage format](https://github.com/sreway/yametrics/pull/2/commits/bcc518d1be8d949e2baef6b8da0a23b8728e5c06)

2022-06-24 15:13 UTC, sreway commented on internal/server/server.go
> +		}
А вроде в задании было указано несколько сигналов обрабатывать, упростил switch [fix switch signals](https://github.com/sreway/yametrics/pull/2/commits/6e5fca220d07c1ca0de4528201c741b03450692b)

2022-06-24 15:15 UTC, sreway commented on internal/server/server.go
> +	wg.Wait()
[fix unnecessary waitgroup](https://github.com/sreway/yametrics/pull/2/commits/7cf723a44f64c645384b2b16639ab6718bb5ce4a)

2022-06-24 15:16 UTC, sreway commented on internal/server/storage.go
> +	StorageMetrics map[string]map[string]interface{}
[change storage format](https://github.com/sreway/yametrics/pull/2/commits/bcc518d1be8d949e2baef6b8da0a23b8728e5c06)

2022-06-24 21:56 UTC, sreway commented on internal/server/handlers.go
> +	decoder.DisallowUnknownFields()
А в чем заключается опасность?

2022-06-24 21:56 UTC, sreway commented on internal/server/handlers.go
> +	w.Header().Set("content-type", "application/json")
[fix header content-type](https://github.com/sreway/yametrics/pull/2/commits/2d0cca7fab76fce5b13732390678fbf5d8b6e048)

2022-06-24 22:25 UTC, sreway commented on cmd/agent/main.go
> +func init() {
Перенес [change flags init location](https://github.com/sreway/yametrics/pull/2/commits/dbd0a66ff6da4aa63ee2fa7181d6c424b24633a0)

2022-06-24 22:45 UTC, sreway commented on internal/agent/agent.go
> +		endpoint := fmt.Sprintf("http://%s/%s", a.Config.ServerAddress, updateURI)
[change metric endpoint for agent](https://github.com/sreway/yametrics/pull/2/commits/d2d605063d65f18d04f221378806bb582ad46134)

2022-06-25 00:49 UTC, sreway commented on internal/server/storage.go
> +	fileObj, err := os.OpenFile(filePath, flag, 0644)
[change work with file](https://github.com/sreway/yametrics/pull/2/commits/dd81b054e94c851770b47217c1dc193c4cdb1c97)

2022-06-25 18:27 UTC, Perederey approved these changes
👍 , теперь все отлично!
Про переменные в пакете, я напишу в общий чат в чем могут быть проблемы

2022-06-25 20:06 UTC, merged