[SPRINT-3] INC-9-13
sreway/yametrics pull request #3
Opened 2022-07-05 01:04 UTC by sreway

Тесты новые специально не добавлял, так как нет уверенности в корректности имплементации хранилищ метрик, так же вопрос так должно быть [failed pipeline link](https://github.com/sreway/yametrics/runs/7188455305?check_suite_focus=true#step:19:22)?

2022-07-06 19:29 UTC, Perederey requested changes
В целом все отлично, и тема с context понятна и сделана хорошо!

Плюс классно, что стал использовать lock.

Из того, что надо переделать это switch для ошибок и после сразу приму работу.

А так все остальное отлично!

2022-07-06 19:29 UTC, Perederey commented on internal/metrics/metrics.go
> +			return fmt.Errorf("Metric_Valid error: %w", ErrInvalidMetricValue)
мини-замечание,
по-факту ты в случаен counter и gauage возвращаешь одну и туже ошибку. Возможно, что ты можешь сделать — либо возвращать разные ошибки (что удобно при дебаге), либо убрать switch и делать проверку на nil

2022-07-06 19:29 UTC, Perederey commented on internal/metrics/metrics.go
> +	}
может тут дженерики бахнуть

2022-07-06 19:29 UTC, Perederey commented on internal/metrics/metrics_test.go
> +			if got != tt.want && tt.wantErr == false {
автогенерируемый код плохо читается, я бы лучше бы его заменил на testify, как ты сделал выше.

2022-07-06 19:29 UTC, Perederey commented on internal/server/config_test.go
> +			}()
defer в тестах немного странно, но почему- бы и нет)

2022-07-06 19:29 UTC, Perederey commented on internal/server/handlers.go
> +
обычно пробел не ставят после основной функции и проверкой на ошибку

2022-07-06 19:29 UTC, Perederey commented on internal/server/handlers.go
>  		}
сложная обработка ошибки.
Возможно тебе сделать одну структуру для ошибки? 

```go
type ErrMetric struct {
// MetricError хранишь   invalid input metric type либо metric hash либо hash
MetricError string
// MetricType дополнительно указываешь gauge или counter, чтобы для debug было понятно 
MetricType string 
}

func (e ErrMetric) Error() string {
     return fmt.Sprinf("[%s] error %s", e.MetricType, e.MetricError)
}

///

и в самом коде

var metricErr
if errors.As(err, &metricErr) {
     log.Printf("Server_UpdateMetricJSON: %v", metricErr.
}
```

2022-07-06 19:29 UTC, Perederey commented on internal/server/handlers.go
> +	}
немного увлекся switch, надо упросить (описал выше пример)

2022-07-06 19:29 UTC, Perederey commented on internal/server/handlers.go
> +	w.WriteHeader(http.StatusOK)
👍 что-то не нашел место как обратываешь context, но думаю где-то в коде просто уже есть)

2022-07-11 00:15 UTC, sreway commented on internal/metrics/metrics.go
> +			return fmt.Errorf("Metric_Valid error: %w", ErrInvalidMetricValue)
[Fix errors handel](https://github.com/sreway/yametrics/pull/3/commits/6ec2693143e271da1b7d18b790b36310e4979133)

2022-07-11 00:16 UTC, sreway commented on internal/server/handlers.go
>  		}
[Fix errors handel](https://github.com/sreway/yametrics/pull/3/commits/6ec2693143e271da1b7d18b790b36310e4979133)

2022-07-11 00:16 UTC, sreway commented on internal/server/handlers.go
> +	}
[Fix errors handel](https://github.com/sreway/yametrics/pull/3/commits/6ec2693143e271da1b7d18b790b36310e4979133)

2022-07-11 00:16 UTC, sreway commented on internal/server/handlers.go
> +
[Remove spaces before errors handel](https://github.com/sreway/yametrics/pull/3/commits/719328496c06a89639cccb224428a99766bb7c35)

2022-07-11 00:17 UTC, sreway commented on internal/metrics/metrics_test.go
> +			if got != tt.want && tt.wantErr == false {
[Change calc hash via generics](https://github.com/sreway/yametrics/pull/3/commits/48bba750a09ab698d53d20737c92f838958b07b8)

2022-07-11 00:18 UTC, sreway commented on internal/metrics/metrics.go
> +	}
[Change calc hash via generics](https://github.com/sreway/yametrics/pull/3/commits/48bba750a09ab698d53d20737c92f838958b07b8)

2022-07-11 20:50 UTC, Perederey approved these changes
Стало лучше ;) спасибо за PR!

2022-07-12 21:26 UTC, merged